/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M21
 * Generated at: 2018-06-04 07:08:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NavBar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1528076808410L));
    _jspx_dependants.put("jar:file:/E:/Developer/Java/FolhaVerdeWorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FolhaVerde/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425989470000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\t <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write(" \t<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/CSS/Pages.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/CSS/NavBar.css\"/>\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/CSS/RobotoFonts.css\" type=\"text/css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/CSS/IndieFlower.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"LogoHeader\">\r\n");
      out.write("\t\t<table class=\"w3-table TopBarTable\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"LogoImg\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"Controller.do?command=ViewIndex\" class=\"indexLink\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/imgs/LOGO.png\"> <span class=\"NomeEmpresaLogo\"> Folha Verde </span></a>\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td id=\"PersonIcoCol\">\r\n");
      out.write("\t\t\t\t\t<i class=\"material-icons\" id=\"PersonIco\">person</i>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td id=\"shoppingCartIcoCol\">\r\n");
      out.write("\t\t\t\t\t<span class=\"ItensCountNumber\">\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</span><i class=\"material-icons\" id=\"shoppingCartIco\">shopping_cart</i>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"Controller.do\" method=\"post\" role=\"form\">\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<ul class=\"horizontal\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Controller.do?command=ViewSalads\" class=\"SaladTab\" type=\"submit\">Saladas</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Controller.do?command=ViewPlates\" class=\"PlateTab\" type=\"submit\">Pratos</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Controller.do?command=ViewDesserts\" class=\"DessertTab\" type=\"submit\">Sobremesas</a></li>\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input id=\"cartSelectedItensId\" name=\"data[cartSelectedItens]\">\r\n");
      out.write("\t\t<input id=\"cartItensTotalId\" name=\"data[cartItensTotal]\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- JQUERY & BOOTSTRAP  -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- jQuery Reference -->\r\n");
      out.write("\t<!-- <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-ui/jquery-ui.min.js\"></script> -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-ui/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\t\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function () {\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tvar arrayItensCartId = [\"0\"];\r\n");
      out.write("\t    $('#cartSelectedItensId').text(arrayItensCartId); // Adiciona aoinput o valor do array (codigo dos itens)\r\n");
      out.write("\t\t$('#cartSelectedItensId').val(arrayItensCartId); // Adiciona aoinput o valor do array (codigo dos itens)\r\n");
      out.write("\t\t$('#cartItensTotalId').text(0); // Salva no input a quantidade de itens ja passada no carrinho \r\n");
      out.write("\t\t$('#cartItensTotalId').val(0); // Salva no input a quantidade de itens ja passada no carrinho\r\n");
      out.write("\r\n");
      out.write("\t  \t$(\".nav a\").on(\"click\", function(){\r\n");
      out.write("\t  \t   $(\".nav\").find(\".active\").removeClass(\"active\");\r\n");
      out.write("\t  \t   $(this).parent().addClass(\"active\");\r\n");
      out.write("\t  \t});\r\n");
      out.write("\r\n");
      out.write("\t\t// Adiciona ao carrinho\r\n");
      out.write("\t  \t$(\".productData\").on(\"click\", function(event){\r\n");
      out.write("\r\n");
      out.write("\t  \t\tvar selectedItemId = $(this).data(\"prodructid\");\r\n");
      out.write("\r\n");
      out.write("\t  \t\tvar cartItensQtd = $('.ItensCountNumber').text();\r\n");
      out.write("\r\n");
      out.write("\t  \t\tcartItensQtd = parseInt(cartItensQtd) + 1;\r\n");
      out.write("\r\n");
      out.write("\t  \t\t$('.ItensCountNumber').text(cartItensQtd);\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('#cartItensTotalId').text(cartItensQtd); // Salva no input a quantidade de itens ja passada no carrinho \r\n");
      out.write("\t\t\t$('#cartItensTotalId').val(cartItensQtd); // Salva no input a quantidade de itens ja passada no carrinho\r\n");
      out.write("\r\n");
      out.write("\t  \t\taddCartFunction(selectedItemId);\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tfunction addCartFunction(selectedItemId) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tarrayItensCartId.push(selectedItemId);\r\n");
      out.write("\t\t    alert( \"TEST: \" +  arrayItensCartId);\r\n");
      out.write("\t\t    $('#cartSelectedItensId').text(arrayItensCartId); // Adiciona aoinput o valor do array (codigo dos itens)\r\n");
      out.write("\t\t\t$('#cartSelectedItensId').val(arrayItensCartId); // Adiciona aoinput o valor do array (codigo dos itens)\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t//# sourceURL=pen.js\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /NavBar.jsp(25,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty productsCartTotal}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productsCartTotal}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
